image: gcc

build:linux:release:
  stage: build
  variables:
    GIT_DEPTH: "1"
  before_script:
    - |
        apt update && apt -y install libsdl1.2-dev zlib1g-dev libfreetype6-dev libnotify-dev libopus-dev tar gcc
        if [ ! -x ~/bam-0.5.0/bam ]; then
          wget -O ~/bamv0.5.0.tar.gz https://github.com/matricks/bam/archive/v0.5.0.tar.gz
          tar -zxvf ~/bamv0.5.0.tar.gz -C ~/
          cd ~/bam-0.5.0; ./make_unix.sh
          cd $CI_PROJECT_DIR
        fi
  script: 
    - ~/bam-0.5.0/bam client_release
    - ~/bam-0.5.0/bam server_release
  artifacts:
    name: MineTee-$CI_COMMIT_REF_NAME
    paths:
      - data/
      - tw_minetee
      - tw_minetee_srv
      - license.txt
      - storage.cfg
  cache:
    paths:
        - ~/bam-0.5.0/
        
build:linux:debug:
  stage: build
  variables:
    GIT_DEPTH: "1"
  before_script:
    - |
        apt update && apt -y install libsdl1.2-dev zlib1g-dev libfreetype6-dev libnotify-dev libopus-dev tar gcc
        if [ ! -x ~/bam-0.5.0/bam ]; then
          wget -O ~/bamv0.5.0.tar.gz https://github.com/matricks/bam/archive/v0.5.0.tar.gz
          tar -zxvf ~/bamv0.5.0.tar.gz -C ~/
          cd ~/bam-0.5.0; ./make_unix.sh
          cd $CI_PROJECT_DIR
        fi
  script:
    - ~/bam-0.5.0/bam client_debug
    - ~/bam-0.5.0/bam server_debug
  artifacts:
    name: MineTee-$CI_COMMIT_REF_NAME-Debug
    paths:
      - data/
      - tw_minetee_d
      - tw_minetee_srv_d
      - license.txt
      - storage.cfg
  cache:
    paths:
        - ~/bam-0.5.0/
